export const ACTION_TITLE_MAX_LENGTH = 100;

export const BASIC_CARD_BUTTONS_MAX_SIZE = 1;
export const BASIC_CARD_TEXT_MAX_LENGTH = 750;
export const BASIC_CARD_WITH_IMAGE_TEXT_MAX_LENGTH = 500;

export const CAROUSEL_MIN_SIZE = 2;
export const CAROUSEL_MAX_SIZE = 10;

export const CONTENTS_MIN_SIZE = 1;
export const CONTENTS_MAX_SIZE = 50;

export const CURRENCY_CODE_LENGTH = 3;

export const LINE_ITEM_ID_MAX_LENGTH = 64;
export const LINE_ITEM_NAME_MAX_LENGTH = 100;
export const LINE_ITEM_DESCRIPTION_MAX_LENGTH = 1000;
export const LINE_ITEM_NOTE_MAX_LENGTH = 1000;

export const LINK_OUT_SUGGESTION_DESTINATION_NAME_MAX_LENGTH = 20;

export const MERCHANT_ORDER_ID_MAX_LENGTH = 128;

export const ORDER_NOTE_MAX_LENGTH = 1000;

export const RICH_RESPONSE_ITEMS_MIN_SIZE = 1;

export const SIMPLE_RESPONSE_DISPLAY_TEXT_MAX_LENGTH = 640;

export const LEGACY_SUGGESTION_TITLE_MAX_LENGTH = 25;
export const LEGACY_SUGGESTIONS_MAX_SIZE = 8;

export const TABLE_CARD_BUTTONS_MAX_SIZE = 1;

export const USER_NOTIFICATION_TITLE_MAX_LENGTH = 30;
export const USER_NOTIFICATION_TEXT_MAX_LENGTH = 100;

export const USER_STATUS_LABEL_MAX_LENGTH = 50;
