export enum EnumAlexaRequestType {
  PLAYBACKCONTROLLER = 'PLAYBACKCONTROLLER',
  CAN_FULFILL_INTENT = 'CAN_FULFILL_INTENT',
  ON_GAME_ENGINE_INPUT_HANDLER_EVENT = 'ON_GAME_ENGINE_INPUT_HANDLER_EVENT',
  ON_PURCHASE = 'ON_PURCHASE',
  ON_EVENT = 'ON_EVENT',
  ON_REMINDER_EVENT = 'ON_REMINDER_EVENT',
  ON_PERMISSION = 'ON_PERMISSION',
}
